- id: doi:10.1145/3691620.3695056
  type: paper
  title: An Empirical Comparison of Model-Agnostic Techniques for Defect Prediction Models
  date: 2024-10-27
  buttons:
    - type: source
      text: Source
      link: https://github.com/Verssae/NeuroJIT

- id: doi:10.1016/j.jss.2023.111677
  type: paper
  date: 2023-07-01

- id: doi:10.1109/MS.2023.3244204
  type: paper
  date: 2023-02-13

- id: doi:10.1109/SANER56733.2023.00026
  type: paper
  title: An Empirical Comparison of Model-Agnostic Techniques for Defect Prediction Models
  authors:
    - Gichan Lee
    - Scott Uk-Jin Lee
  publisher: 2023 IEEE International Conference on Software Analysis, Evolution and Reengineering (SANER)
  link: https://ieeexplore.ieee.org/document/10123486
  date: 2023-03-21

- id: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11224363
  type: paper
  title: Proposal of Outpatient Flow Optimization System in Tertiary and General Hospitals Using Explainable Digital Twin Simulations
  authors:
    - Gichan Lee
    - Scott Uk-Jin Lee
  publisher: 2022 한국소프트웨어종합학술대회
  link: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11224363
  date: 2022-12-20
  orcid: 0000-0001-8019-8720
